#!/usr/bin/env bun

/**
 * Skill Forge Signal Collection Hook
 *
 * Runs as a Claude Code PostToolUse hook.
 * Detects when skills are used and collects passive feedback signals.
 *
 * Hook config in .mcp.json or settings.json:
 * {
 *   "hooks": {
 *     "PostToolUse": [{
 *       "command": "bun run ${CLAUDE_PLUGIN_ROOT}/hooks/signal-hook.ts",
 *       "event": "PostToolUse"
 *     }]
 *   }
 * }
 */

import { loadFeedbackStore, saveFeedbackStore, recordSignal } from "../shared/signal-collector";
import { join } from "path";

interface HookInput {
  tool_name: string;
  tool_input: Record<string, unknown>;
  tool_output?: string;
  session_id: string;
  project_dir: string;
}

async function main() {
  // Read hook input from stdin
  let input: HookInput;
  try {
    const stdin = await Bun.stdin.text();
    if (!stdin.trim()) return;
    input = JSON.parse(stdin);
  } catch {
    return; // Silently exit if no valid input
  }

  const { tool_name, session_id, project_dir } = input;
  if (!project_dir) return;

  const feedbackPath = join(project_dir, "skill-forge-feedback.json");

  // Check if this is a skill invocation (Skill tool use)
  if (tool_name === "Skill") {
    const skillName = (input.tool_input?.skill as string) || "";
    if (!skillName) return;

    // Only track skills that were generated by skill-forge
    // Check if the skill name matches a known forge-generated skill
    const store = await loadFeedbackStore(feedbackPath);

    // Record skill_used signal
    recordSignal(store, skillName, "skill_used", `Skill "${skillName}" was invoked`, session_id);

    // If the tool completed without errors, record a clean completion
    if (input.tool_output && !input.tool_output.includes("error") && !input.tool_output.includes("Error")) {
      recordSignal(store, skillName, "completed_cleanly", "Skill completed without error signals", session_id);
    }

    await saveFeedbackStore(feedbackPath, store);
  }
}

main().catch(() => {
  // Hook must never crash or block Claude Code
});
